CREATE DATABASE LIVRARIA;
GO
USE LIVRARIA;
GO
CREATE TABLE EDITORA(
    CODIGO INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_EDITORA PRIMARY KEY(CODIGO)    
);
GO
CREATE TABLE ASSUNTO(
    SIGLA CHAR(3) NOT NULL,
    DESCRICAO VARCHAR(50),
    CONSTRAINT PK_ASSUNTO PRIMARY KEY(SIGLA)
);
GO
CREATE TABLE AUTOR(
    MATRICULA INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE NULL,
    NACIONALIDADE VARCHAR(50) NULL,
    CONSTRAINT PK_AUTOR PRIMARY KEY(MATRICULA)
);
GO
CREATE TABLE LIVRO(
    CODIGO INT NOT NULL,
    TITULO VARCHAR(50) NOT NULL,
    DATA_LANCAMENTO DATE NULL,
    VALOR MONEY NULL,
    DATA_HORA_CADASTRO DATETIME NOT NULL DEFAULT GETDATE(),
    ATIVO BIT NOT NULL DEFAULT 1,
    COD_EDITORA INT NOT NULL,
    SIGLA_ASSUNTO CHAR(3) NOT NULL,
    CONSTRAINT PK_LIVRO PRIMARY KEY(CODIGO),
    CONSTRAINT FK_LIVRO_EDITORA FOREIGN KEY(COD_EDITORA) 
        REFERENCES EDITORA(CODIGO),
    CONSTRAINT FK_LIVRO_ASSUINTO FOREIGN KEY(SIGLA_ASSUNTO)
        REFERENCES ASSUNTO(SIGLA)    
);
GO
CREATE TABLE AUTORIA(
    COD_LIVRO INT NOT NULL,
    MAT_AUTOR INT NOT NULL,
    CONSTRAINT PK_AUTORIA PRIMARY KEY(COD_LIVRO,MAT_AUTOR),
    CONSTRAINT FK_AUTORIA_LIVRO FOREIGN KEY(COD_LIVRO)
        REFERENCES LIVRO(CODIGO),
    CONSTRAINT FK_AUTORIA_AUTOR FOREIGN KEY(MAT_AUTOR)
        REFERENCES AUTOR(MATRICULA)      
);