CREATE DATABASE LOJA;
GO
USE LOJA;
GO

-- NÃO EXECUTAR O SCRIPT COMPLETAMENTE, POIS É NECESSÁRIO,
-- APÓS A CRIAÇÃO DA DATABASE, CLIAR A FUNÇÃO DE VALIDAR CPF

CREATE TABLE CLIENTE(
    ID INT NOT NULL IDENTITY,
    NOME VARCHAR(50) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF CHAR(11) NOT NULL,
    DATA_HORA_CADASTRO DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID),
    CONSTRAINT CK_CLIENTE_DATA_NASCIMENTO 
        CHECK(DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())>=18),
    CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF),
    CONSTRAINT CK_CLIENTE_CPF CHECK(DBO.FN_VALIDACPF(CPF)=1)
);
GO
CREATE TABLE PRODUTO(
    ID INT NOT NULL IDENTITY,
    NOME VARCHAR(50) NOT NULL,
    VALOR MONEY NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY(ID),
    CONSTRAINT CK_PRODUTO_QUANTIDADE_ESTOQUE CHECK(QUANTIDADE_ESTOQUE>=0)
);
GO
CREATE TABLE PEDIDO(
    ID INT NOT NULL IDENTITY,
    DATA_PEDIDO DATE NOT NULL,
    VALOR MONEY NOT NULL,
    VALOR_PAGO MONEY NULL,
    DATA_PAGAMENTO DATE NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY(ID),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID)
);
GO
CREATE TABLE ITEM_PEDIDO(
    ID_PRODUTO INT NOT NULL,
    ID_PEDIDO INT NOT NULL,
    QUANTIDADE SMALLINT NOT NULL,
    VALOR_PAGO_UNIDADE REAL NOT NULL,
    CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY(ID_PRODUTO, ID_PEDIDO),
    CONSTRAINT FK_ITEM_PEDIDO_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID),
    CONSTRAINT FK_ITEM_PEDIDO_PEDIDO FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID),
    CONSTRAINT CK_ITEM_PEDIDO_QUANTIDADE CHECK(QUANTIDADE>=1)
);








