USE CONSTRUTORA;

-- ADICIONA UM NOVO ATRIBUTO EM TABELA JÁ EXISTENTE
-- ATRIBUTO RG CHAR(9) OPCIONAL NA TABELA FUNCIONARIO
ALTER TABLE FUNCIONARIO ADD RG CHAR(9) NULL;

-- ALTERA A NULABILIDADE DE UM ATRIBUTO JÁ EXISTENTE
-- ALTERAR ATRIBUTO RG DA TABELA FUNCIONARIO PARA OBRIGATORIO
ALTER TABLE FUNCIONARIO ALTER COLUMN RG CHAR(9) NOT NULL;

-- ALTERA TIPO DE DADO DO ATRIBUTO NOME DE FUNCIONARIO PARA VARCHAR(100) - OBRIGATORIO
ALTER TABLE FUNCIONARIO ALTER COLUMN NOME VARCHAR(100) NOT NULL;

-- REMOVE O ATRIBUTO RG DA TABELA FUNCIONARIO
ALTER TABLE FUNCIONARIO DROP COLUMN RG;

-- APAGA UMA CONSTRAINT DE UMA TABELA
-- REMOVER CONSTRAINT DE FK DA TABELA DEPENDENTE QUE REFERENCIA FUNCIONARIO
ALTER TABLE DEPENDENTE DROP CONSTRAINT FK_DEPENDENTE_FUNCIONARIO;

-- CRIA UMA CONSTRAINT EM UMA TABELA JÁ EXISTENTE
-- RECRIA A CONSTRAINT DE FK DE DEPENDENTE REFERENCIANDO FUNCIONARIO
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO)
    REFERENCES FUNCIONARIO(CODIGO);

-- CRIA UMA TABELA DE DEPARTAMENTOS
CREATE TABLE DEPARTAMENTO(
    CODIGO INT NOT NULL IDENTITY,
    NOME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(CODIGO)
);

-- ADICIONAR UM ATRIBUTO PARA VINCULAR FUNCIONARIO COM DEPARTAMENTO
ALTER TABLE FUNCIONARIO ADD COD_DEPARTAMENTO INT NULL;

-- TRANSFORMA O ATRIBUTO CRIADO EM FK PARA DEPARTAMENTO
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO 
    FOREIGN KEY(COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO);

-- transforma o atributo criado em obrigatório
ALTER TABLE FUNCIONARIO ALTER COLUMN COD_DEPARTAMENTO INT NOT NULL;

-- DESATIVA A CONSTRAINT DE FK DE FUNCIONARIO PARA DEPARTAMENTO
ALTER TABLE FUNCIONARIO NOCHECK CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO;

-- RE-ATIVA A CONSTRAINT DE FK DE FUNCIONARIO PARA DEPARTAMENTO
ALTER TABLE FUNCIONARIO CHECK CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO;

-- APAGA CONTRAINT DE FK DE FUNCIONARIO PARA DEPARTAMENTO
ALTER TABLE FUNCIONARIO DROP CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO;

-- APAGA A TABELA DEPARTAMENTO
DROP TABLE DEPARTAMENTO;

-- REMOVE ATRIBUTO COD_DEPARTAMENTO DA TABELA FUNCIONARIO
ALTER TABLE FUNCIONARIO DROP COLUMN COD_DEPARTAMENTO;

-- APAGA O BANCO DE DADOS
DROP DATABASE CONSTRUTORA;
