-- DML SELECT
USE CONSTRUTORA_INSERTS;

-- SELECIONA TODAS AS COLUNAS DA TABELA
SELECT * FROM FUNCIONARIO;

SELECT * FROM DEPENDENTE

-- ESPECIFICANDO AS COLUNAS DO RESULTADO
SELECT CODIGO, NOME, CIDADE, UF FROM FUNCIONARIO;

-- APRESENTE O CODIGO, NOME, DATA DE NASCIMENTO, ATIVO E CIDADE
-- DE TODOS OS FUNCIONÁRIOS ATIVOS DA CIDADE DE TAQUARITINGA
SELECT CODIGO, NOME, DATA_NASCIMENTO, ATIVO, CIDADE 
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA';

-- APRESENTE O CODIGO, NOME, DATA DE NASCIMENTO, ATIVO, CIDADE E SEXO
-- DE TODOS OS FUNCIONÁRIOS ATIVOS DA CIDADE DE TAQUARITINGA.
-- ORDENE EM ORDEM CRESCENTE DE NOME DE FUNCIONÁRIO
-- ASC SINALIZA ORDENAÇÃO CRESCENTE
SELECT CODIGO, NOME, DATA_NASCIMENTO, ATIVO, CIDADE, SEXO
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA'
ORDER BY NOME ASC;

-- APRESENTE O CODIGO, NOME, DATA DE NASCIMENTO, ATIVO, CIDADE E SEXO
-- DE TODOS OS FUNCIONÁRIOS ATIVOS DA CIDADE DE TAQUARITINGA.
-- ORDENE EM ORDEM DECRESCENTE DE NOME DE FUNCIONÁRIO
-- DESC SINALIZA ORDENAÇÃO DECRESCENTE
SELECT CODIGO, NOME, DATA_NASCIMENTO, ATIVO, CIDADE, SEXO
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA'
ORDER BY NOME DESC;


-- APRESENTE O CODIGO, NOME, DATA DE NASCIMENTO, ATIVO, CIDADE E SEXO
-- DE TODOS OS FUNCIONÁRIOS ATIVOS DA CIDADE DE TAQUARITINGA.
-- ORDENE EM ORDEM CRESCENTE DE SEXO E DECRESCENTE DE NOME DE FUNCIONÁRIO
-- DESC SINALIZA ORDENAÇÃO DECRESCENTE
SELECT CODIGO, NOME, DATA_NASCIMENTO, ATIVO, CIDADE, SEXO
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA'
ORDER BY SEXO ASC, NOME DESC;


-- APRESENTE O CODIGO, NOME, DATA DE NASCIMENTO, ATIVO, CIDADE E SEXO
-- DE TODOS OS FUNCIONÁRIOS ATIVOS DA CIDADE DE TAQUARITINGA.
-- ORDENE EM ORDEM DECRESCENTE DE SEXO E CRESCENTE DE NOME DE FUNCIONÁRIO
-- DESC SINALIZA ORDENAÇÃO DECRESCENTE
SELECT CODIGO, NOME, DATA_NASCIMENTO, ATIVO, CIDADE, SEXO
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA'
ORDER BY 6 DESC, 2 ASC;

-- APRESENTE O CODIGO, NOME, DATA DE NASCIMENTO, ATIVO, CIDADE, SEXO E IDADE
-- DE TODOS OS FUNCIONÁRIOS ATIVOS. ORDENE EM ORDEM CRESCENTE DE NOME DE FUNCIONÁRIO
SELECT CODIGO, NOME, DATA_NASCIMENTO, ATIVO, CIDADE, SEXO
    , DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) IDADE
FROM FUNCIONARIO
WHERE ATIVO=1
ORDER BY NOME;

-- APRESENTE O CÓDIGO DO FUNCIONARIO, O NOME, A IDADE, O MÊS DE NASCIMENTO,
-- O ANO DE NASCIMENTO, A DATA DE NASCIMENTO (DD/MM/AAAA) E SALÁRIO (R$), 
-- PARA TODOS OS FUNCIONÁRIOS COM 21 ANOS OU MAIS, ORDENADOS POR DATA DE NASC.
SELECT CODIGO
, NOME
, DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) IDADE
, MONTH(DATA_NASCIMENTO) MES_NASC
, YEAR(DATA_NASCIMENTO) ANO_NASC
, FORMAT(DATA_NASCIMENTO,'d','PT-BR') DATA_NASCIMENTO
, FORMAT(DATA_NASCIMENTO,'D','PT-BR') DATA_NASC_EXTENSO
, FORMAT(SALARIO,'C','PT-BR') SALARIO
FROM FUNCIONARIO
WHERE DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())>=21
ORDER BY FUNCIONARIO.DATA_NASCIMENTO

-- APRESENTE O CÓDIGO DO PROJETO, O NOME, A DATA DE INÍCIO (BR), A DATA DE TÉRMINO (BR),
-- O VALOR (BR), E UMA COLUNA APRESENTANDO SIM/NÃO COM NOME "PROJETO_FINALIZADO".
-- PROJETO FINALIZADO OCORRE SE O PROJETO TEM DATA DE TÉRMINO PREENCHIDA E MENOR OU IGUAL
-- A DATA ATUAL.
SELECT CODIGO
, NOME
, FORMAT(DATA_INICIO,'d','PT-BR') DATA_INI
, FORMAT(DATA_TERMINO,'d','PT-BR') DATA_FIM
, FORMAT(VALOR,'C','PT-BR') VALOR
, CASE
    WHEN(DATA_TERMINO<=GETDATE()) THEN 'SIM'
    ELSE 'NÃO'
END PROJETO_FINALIZADO
FROM PROJETO







