/*
Para os enunciados apresentados, faça os comandos SQL e anexe em arquivo único contendo todos os comandos criados. 
Obs: coloque comentários no arquivo identificando cada questão.

1 -  FAÇA UM UPDATE PARA INATIVAR OS FUNCIONÁRIOS. CONSIDERE SOMENTE
FUNCIONÁRIOS ATIVOS DO SEXO MASCULINO QUE NÃO SEJAM DA CIDADE DE TAQUARITINGA,
QUE TENHAM IDADE MENOR OU IGUAL A 28 ANOS E QUE NÃO TENHAM NASCIDO NO MESES
DE MARÇO A JULHO.
*/
UPDATE FUNCIONARIO SET ATIVO=0 
WHERE ATIVO=1 AND SEXO='M' AND CIDADE!='TAQUARITINGA' AND DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())<=28
AND MONTH(DATA_NASCIMENTO) BETWEEN 3 AND 7;

SELECT * FROM FUNCIONARIO;

/*
2 - FAÇA UM DELETE PARA REMOVER TOODS OS DEPENDENTES COM MAIS DE 18 ANOS.
*/
DELETE FROM DEPENDENTE WHERE DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())>=18;

SELECT * FROM DEPENDENTE;

/*
3 - APRESENTE O NOME DO FUNCIONÁRIO, A IDADE, CPF, EMAIL, SALARIO (BR), DATA_NASCIMENTO (BR), CIDADE E UF.
CONSIDERE SOMENTE FUNCIONÁRIOS RESIDENTES NAS CID. DE TAQUARINGA OU JABOTICABAL, ESTADO DE SP, E QUE
TENHAM 26 ANOS OU MAIS. ORDENE ORDEM DECRESCENTE DE NOME.
*/
SELECT NOME
    , DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) IDADE
    , CPF
    , EMAIL
    , FORMAT(SALARIO,'C','PT-BR') SALARIO
    , FORMAT(DATA_NASCIMENTO,'d','PT-BR') DATA_NASC
    , CIDADE
    , UF
FROM FUNCIONARIO
-- WHERE (CIDADE='TAQUARITINGA' OR CIDADE='JABOTICABAL') AND UF='SP'
WHERE CIDADE IN('TAQUARITINGA','JABOTICABAL') AND UF='SP' AND DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())>=26
ORDER BY NOME DESC;

/*
4 - APRESENTE O CÓDIGO DO FUNCIONÁRIO, NOME, IDADE E A DESCRIÇÃO DA FAIXA ETÁRIA, SENDO AS FAIXAS
ETÁRIAS:

'ATÉ 18 ANOS'
'19 ATÉ 24 ANOS'
'DE 25 A 34 ANOS'
'DE 35 A 49 ANOS'
'DE 50 A 64 ANOS'
'A PARTIR DE 65 ANOS'.

CONSIDERE SOMENTE FUNCIONÁRIOS ATIVOS. ORDENE POR FAIXA ETÁRIA.
*/
SELECT CODIGO, NOME, DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) IDADE
, CASE  
    WHEN(DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())<=18) THEN 'ATÉ 18 ANOS'
    WHEN(DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())<=24) THEN '19 A 24 ANOS'
    WHEN(DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())<=34) THEN '25 A 34 ANOS'
    WHEN(DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())<=49) THEN '35 A 49 ANOS'
    WHEN(DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())<=64) THEN '50 A 64 ANOS'
    ELSE 'A PARTIR DE 65 ANOS'
END FAIXA_ETARIA
FROM FUNCIONARIO
WHERE ATIVO=1
ORDER BY DATA_NASCIMENTO DESC;


/*
5 – CONSIDERANDO A TABELA PROJETO, APRESENTE O CODIGO, NOME, VALOR (BR) E UMA INFORMAÇÃO SOBRE
A DATA DE INICIO QUE PODE SER “A INICIAR EM DD/MM/AAAA” OU “INICIADO EM DD/MM/AAAA”
(ANALISANDO SE A DATA DE INÍCIO DO PROJETO É UMA DATA FUTURA).
INSIRA NOVOS PROJETOS COM DATA DE INÍCIO FUTURA PARA TESTAR A SELECT.
CONSIDERE SOMENTE PROJETOS COM DATA DE TÉRMINO NÃO DEFINIDA. ORDENE EM ORDEM CRESCENTE DE NOME.
*/
SELECT CODIGO
, NOME
, FORMAT(VALOR,'C', 'PT-BR') VALOR
, CASE 
    WHEN(DATA_INICIO>GETDATE()) THEN 'A INICIAR EM '
    ELSE 'INICIADO EM '
END + FORMAT(DATA_INICIO,'d','PT-BR') INICIO
FROM PROJETO
WHERE DATA_TERMINO IS NULL
ORDER BY NOME;


SELECT * FROM PROJETO ORDER BY DATA_INICIO DESC